### ISSUE TITLE
gemeentes met zelfde naam

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#1]
ik zie in de db-tabel bv.

```
(2860, 8400, 'Zandvoorde (Oostende)'),
(2861, 8980, 'Zandvoorde (Zonnebeke)'),
```
deze gaan nooit matchen met plaatsnamen in FB-posts, dus ik denk dat we daar

```
(2860, 8400, 'Zandvoorde'),
(2861, 8980, 'Zandvoorde'),
```
van moeten maken?

**Comment by thunderbug** [comment]
Ja verander dit maar, ik had deze van het internet geplukt zonder echt veel te controleren

**Comment by futtta** [comment]
OK, maar ik kan enkel in de wiki veranderen, niet in jouw DB :-)

**Comment by futtta** [comment]
aangepast, closing
