### ISSUE TITLE
[cron.php] Steden met verschillende postcodes

### ISSUE THREAD

**Issue by thunderbug** [futtta/boekenzoekers#10]
Wat te doen met steden met verschillende postcodes?

![image](https://user-images.githubusercontent.com/568028/30567362-4d76dccc-9cd0-11e7-824e-b9527b33ced5.png)

**Comment by futtta** [comment]
aangezien mensen (uitzonderingen daargelaten) op gemeente (naam) zoeken, zou je dat kunnen negeren? wat vind jij?

**Comment by thunderbug** [comment]
Ja dat is het beste denk ik.
Gewoon Antwerpen 2000 in de database laten staan
