### ISSUE TITLE
[cron.php] post niet gevonden

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#11]
zoeken op Hoboken geeft deze
https://www.facebook.com/groups/boekenjagers/permalink/354966554931424/

niet weer. zou ook front-end kunnen zijn natuurlijk.

**Comment by futtta** [comment]
zelfde probleem voor https://www.facebook.com/groups/boekenjagers/permalink/355148781579868/ heist (op den berg)

**Comment by thunderbug** [comment]
Lijkt nu wel te werken ? Zal waarschijnlijk opgelost zijn met de vorige commits

**Comment by futtta** [comment]
:+1:
