### ISSUE TITLE
[integratie] zoeken -> rss-feed

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#12]
om latere integratie makkelijker te maken (en ik denk aan boekenzoekers -> email of notificatie) :-)

**Comment by futtta** [comment]
als (wanneer) we dit doen, kun je je database-query en je presentatie-logica (momenteel beiden in `drawPosts()`) best opsplitsen waarbij je een `getPostsFromDB()` hebt die wordt opgeroepen door `drawPosts()` and `drawRss()`. ofzo .. ;-)

**Comment by futtta** [comment]
kon me niet houden, cfr. [deze commit](https://github.com/futtta/boekenzoekers/commit/56c0d91c236439df0ddc8e8fea4d74aee60c8db9) :-)

kuis gerust op waar nodig (en voeg docblocks enzo toe)

**Comment by thunderbug** [comment]
Toch al wat minder dat ik moet doen :)
