### ISSUE TITLE
[front-end] "admin" gebruiker kan post deleten

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#13]
zie dat (vanzelfsprekend) spam ook in de db gaat, cfr. http://dev.thunderbug.be/boekenzoekers/?gemeente=heer en idealiter kunnen "admin"-gebruikers die deleten zonder in de db te zitten. 

ik zou hier geen volwaardig login (inclusief gebruikers-creatie en wachtwoorden en ....) voor maken, maar misschien mits een geheime parameter in de URL (`/index.php?user=wim&pwd=qlkjq82Lkjso98` waarbij `wim` en `qlkjq82Lkjso98` in de config file zit) de bezoeker als admin beschouwen? en in dat geval een vuilnisbakje aan elke rij toevoegen om die specifieke post te deleten (elke delete-actie moet ook checken op user & pwd).

**Comment by thunderbug** [comment]
Omdat we de facebook api gebruiken, zouden we de login van facebook niet kunnen gebruiken? Ik moet nog wel een opzoeken of dit mogelijk is zonder in te loggen op de website of al teveel op te slagen in de database.

**Comment by futtta** [comment]
goh, dit is sowieso laagste prioriteit, so ... :)

**Comment by futtta** [comment]
zou overigens kunnen dat ik "boekenzoekers" in de boekenjagers wordpress site integreer en dat ik dan de wordpress user-functies gebruik om te zien of de gebruiker admin is of niet, dus hier moet je idd niet teveel tijd in steken.
