### ISSUE TITLE
[front-end] URL Rewrite search

### ISSUE THREAD

**Issue by thunderbug** [futtta/boekenzoekers#16]
URL Rewrite gebruiken om /zoek/gemeentenaam te maken ipv ?gemeente= dat staat altijd wat mooier

**Comment by futtta** [comment]
altijd leuk, maar low priority :)

**Comment by thunderbug** [comment]
Aangezien we vooral via json werken, is dit niet echt een vereiste :) 

Misschien in de toekomst voor nu gewoon close
