### ISSUE TITLE
[frontend] zoeken op gemeente; identieke resultaten voor alle postcodes van die gemeente

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#17]
cfr. screenshot;
![image](https://user-images.githubusercontent.com/181297/30666152-b4dcbc7c-9e53-11e7-9c9d-19b60466b3b6.png)

wat we misschien kunnen doen; als we zoeken op gemeente; en als we voor dezelfde FB-post (id) meerdere entries hebben, tonen we enkel de eerste (of die entry waarvan de postcode overeenkomt met de vernoemde gemeente, 2000 in het geval van antwerpen)

**Comment by thunderbug** [comment]
mijn test database is niet up-to-date, ik er maar 1 Antwerpen meer instaan op de wiki

**Comment by futtta** [comment]
ik veronderstel dat je de database manueel geleegd hebt nu? :)

**Comment by thunderbug** [comment]
ja ik had de db geleegd
