### ISSUE TITLE
[cron.php] (de|het|een)\splaatsnaam niet opslaan op plaatsnaam

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#18]
post niet opslaan op (de|het|een)\splaatsnaam (bv. verstopt onder een boom <> gemeente boom)

**Comment by futtta** [comment]
zie jij dat zitten @thunderbug ? :-)

**Comment by thunderbug** [comment]
Jup maar zal na het weekend zijn :)

Op 29 sep. 2017 21:26 schreef "frank goossens" <notifications@github.com>:

**Comment by futtta** [comment]
no problem, we zijn niet gehaast :-)

**Comment by thunderbug** [comment]
Voilla dit is nu ook in orde, nog eventjes kijken of het wel degelijk ok is in de volgende dagen
