### ISSUE TITLE
[database] indexen?

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#19]
zouden we geen index zetten op "zipcode", "gemeente" en "auteur" @thunderbug ?

**Comment by thunderbug** [comment]
Done, maakt het idd sneller

**Comment by futtta** [comment]
pas jij https://github.com/futtta/boekenzoekers/wiki/SQL-Database nog aan, kwestie van alles proper gedocumenteerd te hebben? :)

**Comment by thunderbug** [comment]
done
