### ISSUE TITLE
[cron.php] post met 2 plaatsen wordt enkel op 1ste plaats gevonden

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#4]
cfr. 
http://dev.thunderbug.be/boekenzoekers/?gemeente=sint-niklaas -> gevonden met "zele" in tekst, maar
http://dev.thunderbug.be/boekenzoekers/?gemeente=zele -> niet gevonden

**Comment by futtta** [comment]
is vanzelfsprekend een cron.php probleem, geen front-end issue

**Comment by futtta** [comment]
Mijn fout; in "solution design" stond dan ook

> wat doen we met posts met 2 locaties (vb. lokeren eksaarde)? ik zou in de eerste versie stoppen met door de lijst gemeentes te lopen als we een hit hebben, later aan te passen ..

maar denk dat "later" eerder "nu" moet worden, aangezien het toch zo goed vooruit gaat ;-)

**Comment by thunderbug** [comment]
Ik zal de loop met zoeken gewoon niet onderbreken, en laten toevoegen
wanneer er 2 meer of meer plaatsen instaan

Op 18 sep. 2017 3:40 p.m. schreef "frank goossens" <notifications@github.com

**Comment by futtta** [comment]
je zult je count
`
$count = $database->count("posts", array("postID" => $id[1]));`

dan ook wel moeten aanpassen om rekening te houden met verschillende gemeentes.
