### ISSUE TITLE
[front-end] datum in "normaal" format

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#5]
iets als 

```php
date_default_timezone_set("Europe/Brussels");
return strftime("%d/%m/%Y om %H:%M",strtotime($input));
```

geeft 

> 21/08/2017 om 16:42

**Comment by thunderbug** [comment]
Zou ik voor de dag zelf gewoon het aantal uren geleden laten opkomen ? Of gewoon zoals nu Vandaag om 17:15 bijvoorbeeld.

**Comment by futtta** [comment]
Goed idee!

Vandaag om 17h13
Gisteren om 9h57
En dan voor eergisteren en later de gewone datum?

**Comment by thunderbug** [comment]
Jup, dat komt in orde :)

**Comment by futtta** [comment]
reopen; uur zit er blijkbaar een uur naast, cfr. https://www.facebook.com/permalink.php?id=173371763090905&v=wall&story_fbid=355155178245895 die volgens FB om 10h24 werd gepost maar op http://dev.thunderbug.be/boekenzoekers/?gemeente=berlaar als 9h24
