### ISSUE TITLE
[cron.php] [frontend] sint-niklaas vs sint niklaas vs st-niklaas

### ISSUE THREAD

**Issue by futtta** [futtta/boekenzoekers#9]
kunnen we dat generiek en min of meer performant oplossen dat al die variaties als "sint-niklaas" worden herkend?

**Comment by thunderbug** [comment]
Ik kan een wanneer een - teken in de naam staat ook op een spatie controleren.
En bij sint in de naam ook controleren op st ?

**Comment by futtta** [comment]
👍

**Comment by thunderbug** [comment]
Ik heb een vermoeden dat de codering nog niet OK werkt dus nog eventjes opvolgen

**Comment by futtta** [comment]
je doet nu
`
 $tRow["name"] = str_replace("-", "", $tRow["name"]);`

moet dat neit eerder
` $tRow["name"] = str_replace("-", " ", $tRow["name"]);`

zijn?

**Comment by thunderbug** [comment]
jup, dat was het foutje dus +1

**Comment by futtta** [comment]
super! voeg je die logica ook toe in [frontend]?

**Comment by futtta** [comment]
wat als je -in het voorbeeld van sint-niklaas- iets als dit gebruikt;
```php
/(st\.?|sint)[-|\s]niklaas/
```
cfr. https://regex101.com/r/LqZWvZ/1

dus je zou je $row kunnen opbouwen:
* als spatie or koppelteken in gemeentenaam: [-|\s]
* als sint (gevolgd door spatie of koppelteken): (st\.?|sint)

en dan moet je maar 1 ipv (max) 4 checkNameInText() doen?

**Comment by thunderbug** [comment]
Dat is inderdaad interessant!

**Comment by futtta** [comment]
werkt super! zou wel nog iets gelijksaardigs moeten hebbben voor "bergen-op-zoom" vs "bergen op zoom" of "watermael bosvoorde" vs "watermael-bosvoorde", dus spaties worden koppeltekens en omgekeerd? :-)

**Comment by futtta** [comment]
+bugje: in de "gemeente"-kolom in de frontend staat nu bv. `Sint[-|\s]Andries`

![image](https://user-images.githubusercontent.com/181297/30631607-149fd5be-9de5-11e7-9f9a-d10d30abec96.png)

**Comment by thunderbug** [comment]
Ziezo, nu zou het opgelost moeten zijn.
Voor bergen-op-zoom etc had ik al erin gemaakt

**Comment by futtta** [comment]
`sint gilles dendermonde` in tekst wordt enkel gevonden met "dendermonde" (eerste entry, vandaag 10h52), maar niet met "sint-gilles" of "sint gillis" (cfr. 2de screenshot)?

![image](https://user-images.githubusercontent.com/181297/30707354-8960c3ce-9efb-11e7-81b8-e98318031e1d.png)

![image](https://user-images.githubusercontent.com/181297/30707427-c36219e2-9efb-11e7-8a2b-a37c24b7c75a.png)

**Comment by thunderbug** [comment]
Ik heb een fix gecommit voor Sint-Gilles
